"""initial portfolio tables

Revision ID: ad5360b125b8
Revises: 
Create Date: 2026-07-05 17:40:03.352616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ad5360b125b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('institution', sa.Text(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio'
    )
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio'
    )
    op.create_index(op.f('ix_portfolio_admin_users_username'), 'admin_users', ['username'], unique=True, schema='portfolio')
    op.create_table('diagrams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagram_key', sa.Text(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('edges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio'
    )
    op.create_index(op.f('ix_portfolio_diagrams_diagram_key'), 'diagrams', ['diagram_key'], unique=True, schema='portfolio')
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('client', sa.Text(), nullable=True),
    sa.Column('duration', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio'
    )
    op.create_index(op.f('ix_portfolio_experiences_slug'), 'experiences', ['slug'], unique=True, schema='portfolio')
    op.create_table('homelab_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_key', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('hardware', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio'
    )
    op.create_index(op.f('ix_portfolio_homelab_devices_device_key'), 'homelab_devices', ['device_key'], unique=True, schema='portfolio')
    op.create_table('profile',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('tagline', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('bio', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('socials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='profile_singleton'),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio'
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('repo_url', sa.Text(), nullable=True),
    sa.Column('live_url', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio'
    )
    op.create_index(op.f('ix_portfolio_projects_slug'), 'projects', ['slug'], unique=True, schema='portfolio')
    op.create_table('skill_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio'
    )
    op.create_table('homelab_containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_key', sa.Text(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('resources', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['portfolio.homelab_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio'
    )
    op.create_index(op.f('ix_portfolio_homelab_containers_container_key'), 'homelab_containers', ['container_key'], unique=True, schema='portfolio')
    op.create_table('homelab_network_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['portfolio.homelab_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio'
    )
    op.create_table('homelab_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.Text(), nullable=False),
    sa.Column('container_name', sa.Text(), nullable=True),
    sa.Column('host_port', sa.Text(), nullable=True),
    sa.Column('function', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['portfolio.homelab_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio'
    )
    op.create_table('project_case_studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('client', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('duration', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('platform', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('layers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['portfolio.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id'),
    schema='portfolio'
    )
    op.create_table('project_deliverables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('deliverable_key', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('tag', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['portfolio.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'deliverable_key', name='uq_project_deliverable'),
    schema='portfolio'
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['portfolio.skill_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills', schema='portfolio')
    op.drop_table('project_deliverables', schema='portfolio')
    op.drop_table('project_case_studies', schema='portfolio')
    op.drop_table('homelab_services', schema='portfolio')
    op.drop_table('homelab_network_entities', schema='portfolio')
    op.drop_index(op.f('ix_portfolio_homelab_containers_container_key'), table_name='homelab_containers', schema='portfolio')
    op.drop_table('homelab_containers', schema='portfolio')
    op.drop_table('skill_groups', schema='portfolio')
    op.drop_index(op.f('ix_portfolio_projects_slug'), table_name='projects', schema='portfolio')
    op.drop_table('projects', schema='portfolio')
    op.drop_table('profile', schema='portfolio')
    op.drop_index(op.f('ix_portfolio_homelab_devices_device_key'), table_name='homelab_devices', schema='portfolio')
    op.drop_table('homelab_devices', schema='portfolio')
    op.drop_index(op.f('ix_portfolio_experiences_slug'), table_name='experiences', schema='portfolio')
    op.drop_table('experiences', schema='portfolio')
    op.drop_index(op.f('ix_portfolio_diagrams_diagram_key'), table_name='diagrams', schema='portfolio')
    op.drop_table('diagrams', schema='portfolio')
    op.drop_index(op.f('ix_portfolio_admin_users_username'), table_name='admin_users', schema='portfolio')
    op.drop_table('admin_users', schema='portfolio')
    op.drop_table('academic_items', schema='portfolio')
    # ### end Alembic commands ###
